let RESULTS=null;

function formatLocalUpdate(value){
  if(!value)return '—';
  let raw=String(value).trim();
  if(/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}(:\d{2}(\.\d+)?)?$/.test(raw)) raw=raw.replace(' ','T')+'Z';
  const date=new Date(raw);
  if(Number.isNaN(date.getTime()))return value;
  return new Intl.DateTimeFormat('fr-CA',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(date);
}
function escapeHtml(value){return String(value??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function marketRisk(x){const vol=Number(x.volatility_pct),price=Number(x.price),rvol=Number(x.rvol);let score=0;if(Number.isFinite(vol))score+=Math.max(0,Math.min(70,(vol-15)/65*70));else score+=35;if(Number.isFinite(price)){if(price<1)score+=20;else if(price<2)score+=17;else if(price<5)score+=13;else if(price<10)score+=8;else if(price<20)score+=4;}if(Number.isFinite(rvol)){if(rvol>=3)score+=10;else if(rvol>=2)score+=7;else if(rvol>=1.5)score+=4;else if(rvol<0.5)score+=5;}return Math.max(0,Math.min(100,score));}
function riskLabel(score){if(score>=75)return 'spéculatif';if(score>=55)return 'élevé';if(score>=30)return 'modéré';return 'faible';}
function filteredBuyRows(){if(!RESULTS)return[];const riskMax=Number(document.getElementById('riskMax')?.value??100),timingMin=Number(document.getElementById('timingMin')?.value??0);return(RESULTS.buy||[]).filter(x=>{const timing=Number(x.buy_timing??x.timing_v14);return marketRisk(x)<=riskMax&&Number.isFinite(timing)&&timing>=timingMin;}).slice(0,30);}
function applyBuyFilters(){if(!RESULTS)return;const riskMax=Number(document.getElementById('riskMax')?.value??100),timingMin=Number(document.getElementById('timingMin')?.value??0);const riskOut=document.getElementById('riskMaxValue'),timingOut=document.getElementById('timingMinValue');if(riskOut)riskOut.textContent=riskMax.toFixed(0);if(timingOut)timingOut.textContent=timingMin.toFixed(0);const rows=filteredBuyRows(),source=RESULTS.buy||[];const count=document.getElementById('buyFilterCount');if(count)count.textContent=`${rows.length} titre${rows.length===1?'':'s'} affiché${rows.length===1?'':'s'} sur ${source.length}`;render('buyList',rows,'buy');}
function setupBuyFilters(){const risk=document.getElementById('riskMax'),timing=document.getElementById('timingMin');const savedRisk=localStorage.getItem('buyRiskMax'),savedTiming=localStorage.getItem('buyTimingMin');if(risk&&savedRisk!==null)risk.value=savedRisk;if(timing&&savedTiming!==null)timing.value=savedTiming;if(risk)risk.addEventListener('input',()=>{localStorage.setItem('buyRiskMax',risk.value);applyBuyFilters()});if(timing)timing.addEventListener('input',()=>{localStorage.setItem('buyTimingMin',timing.value);applyBuyFilters()});applyBuyFilters();}
function saveRankPdf(){
  const rows=filteredBuyRows();if(!rows.length){alert('Aucun titre affiché à enregistrer.');return;}
  const now=new Date(),yy=String(now.getFullYear()).slice(-2),mm=String(now.getMonth()+1).padStart(2,'0'),dd=String(now.getDate()).padStart(2,'0');const title=`Rank ${yy}-${mm}-${dd}`;
  const riskMax=Number(document.getElementById('riskMax')?.value??100),timingMin=Number(document.getElementById('timingMin')?.value??0);
  const body=rows.map((x,i)=>`<tr><td>${i+1}</td><td><b>${escapeHtml(x.symbol)}</b></td><td>${escapeHtml(x.name||'—')}</td><td>${Number(x.potential_score??x.score).toFixed(1)}</td><td>${Number(x.buy_timing??x.timing_v14).toFixed(1)}</td><td>${marketRisk(x).toFixed(0)}</td><td>${x.price??'—'}</td></tr>`).join('');
  const w=window.open('','_blank');if(!w){alert('Le navigateur a bloqué la fenêtre PDF. Autorise les fenêtres surgissantes pour cette page.');return;}
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>@page{size:A4;margin:14mm}body{font-family:Arial,sans-serif;color:#111}h1{margin:0 0 5px;font-size:22px}.meta{font-size:12px;color:#555;margin-bottom:16px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:6px;border-bottom:1px solid #ddd;text-align:left}th{background:#f2f2f2}td:nth-child(1),td:nth-child(4),td:nth-child(5),td:nth-child(6){text-align:right}</style></head><body><h1>${title}</h1><div class="meta">Liste exacte affichée dans Tableau · Risque maxi ${riskMax} · Timing minimum ${timingMin} · ${rows.length} titres</div><table><thead><tr><th>Rang</th><th>Titre</th><th>Nom</th><th>Potentiel</th><th>Timing</th><th>Risque</th><th>Prix</th></tr></thead><tbody>${body}</tbody></table><script>window.onload=()=>{document.title='${title}';setTimeout(()=>window.print(),250)}<\/script></body></html>`);w.document.close();
}
async function loadResults(){const r=await fetch('data/results.json?'+Date.now(),{cache:'no-store'});const d=await r.json();RESULTS=d;document.getElementById('updated').textContent=`Mise à jour : ${formatLocalUpdate(d.updated)} · ${d.analyzed||0}/${d.universe||0} titres analysés`;setupBuyFilters();document.getElementById('saveRankPdf')?.addEventListener('click',saveRankPdf);const sel=document.getElementById('sellPortfolio');const portfolios=(d.portfolios&&d.portfolios.length)?d.portfolios:[{id:'michel',name:'Michel'},{id:'fils',name:'Loïc'}];sel.innerHTML=portfolios.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');const saved=localStorage.getItem('sellPortfolio');if(saved&&portfolios.some(p=>p.id===saved))sel.value=saved;showSell();sel.addEventListener('change',()=>{localStorage.setItem('sellPortfolio',sel.value);showSell()});const refresh=document.getElementById('forceRefresh');if(refresh)refresh.addEventListener('click',()=>{const body=`STOCK_INDICATOR_REFRESH\n\nDemande de mise à jour forcée depuis Stock Indicator.`;const url=`https://github.com/Seguinstock/indicator/issues/new?title=${encodeURIComponent('Refresh Stock Indicator')}&body=${encodeURIComponent(body)}`;window.open(url,'_blank','noopener');});}
function showSell(){if(!RESULTS)return;const pid=document.getElementById('sellPortfolio')?.value||'michel';const rows=RESULTS.sell_by_portfolio?.[pid]??(pid==='michel'?RESULTS.sell||[]:[]);render('sellList',rows,'sell');}
function render(id,rows,type){const el=document.getElementById(id);el.innerHTML='';if(!rows.length){el.innerHTML=`<div class="empty">${type==='sell'?'Aucun titre détenu analysable dans ce portefeuille.':'Aucun titre ne respecte les seuils choisis.'}</div>`;return}rows.forEach(x=>{const row=document.createElement('details');row.className='stock';const cls=x.country==='CA'?'canada':x.country==='US'?'usa':'other';const labels={rsi:'RSI',reversal:'Rebond RSI',support:'Zone de rebond',rvol:'Volume relatif',macd:'MACD',trend:'Tendance'};const checks=Object.entries(x.filters||{}).map(([k,v])=>`<span class="check ${v?'ok':'no'}">${v?'✓':'✕'} ${labels[k]||k}</span>`).join('');const sale=type==='sell';const comps=x.potential_components||{};const componentText=!sale?`<div class="checks"><span class="check neutral">Volatilité ${comps.volatility??'—'} pts</span><span class="check neutral">Tendance ${comps.trend??'—'} pts</span><span class="check neutral">RVOL ${comps.rvol??'—'} pts</span><span class="check neutral">RSI ${comps.rsi??'—'} pts</span><span class="check neutral">Zone ${comps.support??'—'} pts</span></div>`:'';const potential=Number(x.potential_score??x.score),timing=Number(x.buy_timing??x.timing_v14),risk=marketRisk(x);const buyScoreText=`Potentiel ${Number.isFinite(potential)?potential.toFixed(1):'—'} <span class="score-separator">·</span> Timing ${Number.isFinite(timing)?timing.toFixed(1):'—'} <span class="score-separator">·</span> Risque ${risk.toFixed(0)}`;row.innerHTML=`<summary><span class="symbol ${cls}">${x.symbol}</span><span class="score">${sale?`Score vente ${Number(x.score).toFixed(1)}`:buyScoreText}</span></summary><div class="detail"><div>Nom <b>${escapeHtml(x.name)}</b></div><div>Prix <b>${x.price??'—'}</b></div><div>RSI <b>${x.rsi??'—'}</b></div><div>Δ RSI <b>${x.delta_rsi??'—'}</b></div><div>RVOL <b>${x.rvol??'—'}</b></div><div>Distance de la zone de rebond <b>${x.support_distance_pct??'—'} %</b></div><div>MACD <b>${x.macd_momentum??'—'}</b></div><div>Tendance <b>${x.trend??'—'}</b></div><div>Volatilité <b>${x.volatility_pct??'—'} %</b></div>${sale?`<div>Timing vente <b>${x.sell_timing_v14??'—'}</b></div><div>Signal <b>${x.sell_signal??'—'}</b></div>`:`<div>Score potentiel <b>${x.potential_score??x.score??'—'}</b></div><div>Timing actuel <b>${x.buy_timing??x.timing_v14??'—'}</b></div><div>Risque de marché <b>${risk.toFixed(0)}/100 — ${riskLabel(risk)}</b></div>${componentText}<div class="checks">${checks}</div>`}</div>`;el.appendChild(row);});}
loadResults().catch(e=>{document.getElementById('updated').textContent='Erreur de chargement';console.error(e)});
