const LABELS={rsi:'RSI',reversal:'Rebond RSI',support:'Zone de rebond',rvol:'RVOL',macd:'MACD',trend:'Tendance'};
const PARAM_LABELS={
'buy_model.volatility_weight':'Poids volatilité','buy_model.trend_weight':'Poids tendance','buy_model.rvol_weight':'Poids RVOL','buy_model.rsi_weight':'Poids RSI','buy_model.support_weight':'Poids support','buy_model.volatility_floor_pct':'Volatilité plancher (%)','buy_model.volatility_full_pct':'Volatilité pleine (%)','buy_model.rvol_floor':'RVOL plancher','buy_model.rvol_full':'RVOL plein','buy_model.rsi_target':'RSI cible','buy_model.rsi_range':'Plage RSI','buy_model.support_max_distance_pct':'Distance support max (%)','indicators.rsi_period':'Période RSI','indicators.rvol_period':'Période RVOL','indicators.support_lookback':'Historique support','filters.rsi.buy_max':'Filtre RSI max','filters.reversal.min_delta':'Rebond RSI min','filters.support.max_distance_pct':'Distance support filtre (%)','filters.rvol.min':'RVOL filtre min','filters.macd.min_momentum':'MACD minimum','filters.trend.min':'Tendance minimum'};
let POLL_TIMER=null,REQUESTED_ASOF=null,REQUESTED_END=null,REQUESTED_UNIVERSE=null,PRINT_OPEN_STATE=[];
function fmt(v,d=1){return v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(d)}
function pct(v){return v==null||Number.isNaN(Number(v))?'—':`${Number(v)>=0?'+':''}${Number(v).toFixed(2)} %`}
function tone(v){if(v==null)return'neutral';return v?'ok':'no'}
function universeLabel(mode){return mode==='sp500_pit'?'S&P 500 historique':'Ma liste actuelle'}
function selectedUniverse(){return document.querySelector('input[name="backtestUniverse"]:checked')?.value||'current'}
function flattenParams(obj,prefix='',out=[]){Object.entries(obj||{}).forEach(([k,v])=>{const path=prefix?`${prefix}.${k}`:k;if(v&&typeof v==='object'&&!Array.isArray(v))flattenParams(v,path,out);else out.push([path,v]);});return out;}
function renderParameters(d){const el=document.getElementById('btParameterValues');const snap=d.parameter_snapshot;if(!snap){el.innerHTML='<div>Non disponibles pour les anciens backtests.</div>';return;}const rows=flattenParams(snap).filter(([p])=>PARAM_LABELS[p]);el.innerHTML=rows.map(([p,v])=>`<div><span>${PARAM_LABELS[p]}</span><b>${typeof v==='boolean'?(v?'Activé':'Désactivé'):v}</b></div>`).join('')||'<div>Aucun paramètre enregistré.</div>';}
async function loadBacktest(showFeedback=false){const meta=document.getElementById('btMeta'),reload=document.getElementById('reloadBacktest'),reloadNotice=document.getElementById('reloadNotice');if(showFeedback){reload.disabled=true;reload.textContent='↻ Actualisation…';reloadNotice.textContent='Vérification du dernier résultat…';reloadNotice.className='notice';}try{const r=await fetch('data/backtest.json?'+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Aucun résultat');const d=await r.json(),mode=d.universe_mode||'current';meta.textContent=`Photo du ${d.asof} · observation jusqu’au ${d.end} · ${universeLabel(mode)} · ${d.tested||0}/${d.universe||0} titres`;renderParameters(d);renderSummary(d);renderRows(d.all_rows||d.top_by_score||[]);if(showFeedback){reloadNotice.textContent=`Résultat chargé : ${d.asof} → ${d.end} · ${universeLabel(mode)}`;reloadNotice.className='notice';}if(REQUESTED_ASOF&&d.asof===REQUESTED_ASOF&&d.end===REQUESTED_END&&mode===REQUESTED_UNIVERSE){const n=document.getElementById('requestNotice');n.textContent=`✓ Backtest terminé avec ${universeLabel(mode)}. Les résultats ci-dessous sont à jour.`;n.className='notice';stopPolling();}return d;}catch(e){meta.textContent='Aucun backtest disponible.';document.getElementById('btSummary').innerHTML='';document.getElementById('btList').innerHTML='<div class="empty">Lance un premier backtest.</div>';return null;}finally{if(showFeedback){reload.disabled=false;reload.textContent='↻ Actualiser maintenant';}}}
function equalWeightPortfolio(rows,count){const sample=(rows||[]).slice(0,count).filter(x=>Number.isFinite(Number(x.return_pct)));if(!sample.length)return null;const invested=sample.length,endValue=sample.reduce((s,x)=>s+(1+Number(x.return_pct)/100),0);return{n:sample.length,invested,endValue,gainPct:(endValue/invested-1)*100};}
function renderSummary(d){const rows=d.all_rows||d.top_by_score||[],p30=equalWeightPortfolio(rows,30),p100=equalWeightPortfolio(rows,100);const portfolioCards=[p30&&`<div class="bt-stat portfolio-result"><b>Portefeuille Top 30</b><span class="${p30.gainPct>=0?'ok':'no'}">${pct(p30.gainPct)}</span><small>1 $ par titre · ${p30.invested.toFixed(0)} $ → ${p30.endValue.toFixed(2)} $</small></div>`,p100&&`<div class="bt-stat portfolio-result"><b>Portefeuille Top 100</b><span class="${p100.gainPct>=0?'ok':'no'}">${pct(p100.gainPct)}</span><small>1 $ par titre · ${p100.invested.toFixed(0)} $ → ${p100.endValue.toFixed(2)} $</small></div>`].filter(Boolean).join('');const effects=d.filter_effects||{},order=['macd','rvol','reversal','rsi','support','trend'];const filterCards=order.map(k=>{const x=effects[k];if(!x?.pass||!x?.fail)return'';const diff=Number(x.pass.avg_return_pct)-Number(x.fail.avg_return_pct),cls=diff>.25?'ok':diff<-.25?'no':'neutral';return`<div class="bt-stat"><b>${LABELS[k]||k}</b><span class="${cls}">Passe ${pct(x.pass.avg_return_pct)}</span><small>Échoue ${pct(x.fail.avg_return_pct)} · gagnants ${fmt(x.pass.win_rate_pct)} %</small></div>`;}).join('');document.getElementById('btSummary').innerHTML=portfolioCards+filterCards;}
function renderRows(rows){const el=document.getElementById('btList');el.innerHTML='';if(!rows.length){el.innerHTML='<div class="empty">Aucun titre analysable.</div>';return}rows.slice(0,100).forEach(x=>{const row=document.createElement('details');row.className='stock';const cls=x.country==='CA'?'canada':x.country==='US'?'usa':'other';const checks=Object.entries(x.filters||{}).map(([k,v])=>`<span class="check ${tone(v)}">${v?'✓':'✕'} ${LABELS[k]||k}</span>`).join('');row.innerHTML=`<summary><span class="symbol ${cls}">${x.symbol}</span><span class="score">Score ${fmt(x.score)} · ${pct(x.return_pct)}</span></summary><div class="detail"><div>Prix historique <b>${fmt(x.price,2)}</b></div><div>RSI <b>${fmt(x.rsi)}</b></div><div>Δ RSI <b>${fmt(x.delta_rsi)}</b></div><div>RVOL <b>${fmt(x.rvol,2)}</b></div><div>Zone de rebond <b>${fmt(x.support_distance_pct)} %</b></div><div>MACD <b>${fmt(x.macd_momentum)}</b></div><div>Tendance <b>${fmt(x.trend)}</b></div><div>Volatilité <b>${fmt(x.volatility_pct)} %</b></div><div>Fin de période <b>${pct(x.return_pct)}</b></div><div>Pic observé <b>${pct(x.max_upside_pct)}</b></div><div>Creux observé <b>${pct(x.max_drawdown_pct)}</b></div><div class="checks">${checks}</div></div>`;el.appendChild(row);});}
function setDefaults(){const asof=document.getElementById('asof'),end=document.getElementById('end'),now=new Date(),a=new Date(now);a.setMonth(a.getMonth()-1);const e=new Date(a);e.setDate(e.getDate()+28);const iso=d=>d.toISOString().slice(0,10);asof.value=iso(a);end.value=iso(e);asof.max=iso(new Date(now.getTime()-86400000));asof.addEventListener('change',()=>{if(!asof.value)return;const d=new Date(asof.value+'T12:00:00');d.setDate(d.getDate()+28);end.value=iso(d);});}
function startPolling(){stopPolling();POLL_TIMER=setInterval(()=>loadBacktest(false),15000)}function stopPolling(){if(POLL_TIMER){clearInterval(POLL_TIMER);POLL_TIMER=null}}
function exportPdf(){const rows=[...document.querySelectorAll('#btList details.stock')];if(!rows.length)return;PRINT_OPEN_STATE=rows.map(x=>x.open);rows.forEach(x=>x.open=true);document.body.classList.add('printing-backtest');window.print()}
function restoreAfterPrint(){[...document.querySelectorAll('#btList details.stock')].forEach((x,i)=>x.open=Boolean(PRINT_OPEN_STATE[i]));PRINT_OPEN_STATE=[];document.body.classList.remove('printing-backtest')}
function updateUniverseHint(){document.getElementById('universeHint').textContent=selectedUniverse()==='sp500_pit'?'Reconstruit les sociétés qui faisaient partie du S&P 500 à la date historique choisie. Disponible pour les dates couvertes par l’historique PIT (2021 et après).':'Utilise les titres actuellement activés dans Stock Indicator.'}
function launch(){const asof=document.getElementById('asof').value,end=document.getElementById('end').value,universe=selectedUniverse(),notice=document.getElementById('requestNotice');if(!asof||!end){notice.textContent='Choisis les deux dates.';return}if(end<=asof){notice.textContent='La date d’observation doit être après la date historique.';return}if(universe==='sp500_pit'&&asof<'2021-01-01'){notice.textContent='Le S&P 500 historique point-in-time est disponible à partir de 2021.';return}REQUESTED_ASOF=asof;REQUESTED_END=end;REQUESTED_UNIVERSE=universe;const body=`STOCK_INDICATOR_BACKTEST\n\nBACKTEST_ASOF=${asof}\nBACKTEST_END=${end}\nBACKTEST_UNIVERSE=${universe}\n\nDemande créée depuis la page Backtest de Stock Indicator.`;window.open(`https://github.com/Seguinstock/indicator/issues/new?title=${encodeURIComponent('Run Stock Indicator Backtest')}&body=${encodeURIComponent(body)}`,'_blank','noopener');notice.textContent=`Après confirmation GitHub, le test utilisera ${universeLabel(universe)} et les paramètres actifs à cet instant. Cette page vérifie le résultat toutes les 15 secondes.`;startPolling()}
document.getElementById('runBacktest').addEventListener('click',launch);document.getElementById('reloadBacktest').addEventListener('click',()=>loadBacktest(true));document.getElementById('exportBacktest').addEventListener('click',exportPdf);document.querySelectorAll('input[name="backtestUniverse"]').forEach(x=>x.addEventListener('change',updateUniverseHint));window.addEventListener('afterprint',restoreAfterPrint);setDefaults();updateUniverseHint();loadBacktest(false);